### ISSUE TITLE
kinect2_bridge can not work

### ISSUE THREAD

**Issue by 66loveslife** [GaiTech-Robotics/Ros2Bot#3]
Hello,
when I finish Install kinect2 bridge,input " roslaunch kinect2_bridge kinect2_bridge.launch"，it came out that

[ INFO] [1515332760.994250122]: Loading nodelet /kinect2_bridge of type kinect2_bridge/kinect2_bridge_nodelet to manager kinect2 with the following remappings:
[ INFO] [1515332760.999010608]: waitForService: Service [/kinect2/load_nodelet] has not been advertised, waiting...
process[kinect2_points_xyzrgb_hd-6]: started with pid [22214]
[ INFO] [1515332761.176420516]: Initializing nodelet with 4 worker threads.
[ INFO] [1515332761.180794474]: waitForService: Service [/kinect2/load_nodelet] is now available.
[ INFO] [1515332761.343792683]: [Kinect2Bridge::initialize] parameter:
        base_name: kinect2
           sensor: default
        fps_limit: -1
       calib_path: /home/ubuntu/catkin_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: default
     depth_device: -1
       reg_method: default
       reg_device: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 5
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4
libva info: VA-API version 0.35.0
libva info: va_getDriverName() returns 1
libva error: va_getDriverName() failed with operation failed,driver_name=i965
[Error] [VaapiRgbPacketProcessorImpl] vaInitialize(display, &major_ver, &minor_ver): operation failed
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 11 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @3:5 with serial 003505162447
[Info] [Freenect2Impl] found 1 devices
[ INFO] [1515332761.769877058]: [Kinect2Bridge::initDevice] Kinect2 devices found: 
[ INFO] [1515332761.770150754]: [Kinect2Bridge::initDevice]   0: 003505162447 (selected)
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 20*16384 ir: 60*8*33792
[Info] [Freenect2DeviceImpl] opened
[ INFO] [1515332761.864747705]: [Kinect2Bridge::initDevice] starting kinect2
[Info] [Freenect2DeviceImpl] starting...
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
[ INFO] [1515332762.243044272]: [Kinect2Bridge::initDevice] device serial: 003505162447
[ INFO] [1515332762.243260193]: [Kinect2Bridge::initDevice] device firmware: 4.0.3911.0
[Info] [Freenect2DeviceImpl] stopping...
[Info] [Freenect2DeviceImpl] canceling rgb transfers...
[Info] [Freenect2DeviceImpl] canceling depth transfers...
[Info] [Freenect2DeviceImpl] stopped
[FATAL] [1515332762.847370115]: Failed to load nodelet '/kinect2_points_xyzrgb_hd` of type `depth_image_proc/point_cloud_xyzrgb` to manager `kinect2'
[FATAL] [1515332762.847987274]: Failed to load nodelet '/kinect2_points_xyzrgb_sd` of type `depth_image_proc/point_cloud_xyzrgb` to manager `kinect2'
[FATAL] [1515332762.847991390]: Failed to load nodelet '/kinect2_points_xyzrgb_qhd` of type `depth_image_proc/point_cloud_xyzrgb` to manager `kinect2'
[FATAL] [1515332762.848239275]: Failed to load nodelet '/kinect2_bridge` of type `kinect2_bridge/kinect2_bridge_nodelet` to manager `kinect2'
[kinect2-2] process has died [pid 22186, exit code -11, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=kinect2 __log:=/home/ubuntu/.ros/log/181d7a3a-f3b1-11e7-af8a-ac7ba111b09d/kinect2-2.log].
log file: /home/ubuntu/.ros/log/181d7a3a-f3b1-11e7-af8a-ac7ba111b09d/kinect2-2*.log
[kinect2_points_xyzrgb_qhd-5] process has died [pid 22195, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb kinect2 rgb/camera_info:=kinect2/qhd/camera_info rgb/image_rect_color:=kinect2/qhd/image_color_rect depth_registered/image_rect:=kinect2/qhd/image_depth_rect depth_registered/points:=kinect2/qhd/points __name:=kinect2_points_xyzrgb_qhd __log:=/home/ubuntu/.ros/log/181d7a3a-f3b1-11e7-af8a-ac7ba111b09d/kinect2_points_xyzrgb_qhd-5.log].
log file: /home/ubuntu/.ros/log/181d7a3a-f3b1-11e7-af8a-ac7ba111b09d/kinect2_points_xyzrgb_qhd-5*.log
[kinect2_points_xyzrgb_hd-6] process has died [pid 22214, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb kinect2 rgb/camera_info:=kinect2/hd/camera_info rgb/image_rect_color:=kinect2/hd/image_color_rect depth_registered/image_rect:=kinect2/hd/image_depth_rect depth_registered/points:=kinect2/hd/points __name:=kinect2_points_xyzrgb_hd __log:=/home/ubuntu/.ros/log/181d7a3a-f3b1-11e7-af8a-ac7ba111b09d/kinect2_points_xyzrgb_hd-6.log].
log file: /home/ubuntu/.ros/log/181d7a3a-f3b1-11e7-af8a-ac7ba111b09d/kinect2_points_xyzrgb_hd-6*.log
[kinect2_points_xyzrgb_qhd-5] restarting process
process[kinect2_points_xyzrgb_qhd-5]: started with pid [22372]
[kinect2_points_xyzrgb_hd-6] restarting process
process[kinect2_points_xyzrgb_hd-6]: started with pid [22373]
[kinect2_bridge-3] process has died [pid 22189, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load kinect2_bridge/kinect2_bridge_nodelet kinect2 __name:=kinect2_bridge __log:=/home/ubuntu/.ros/log/181d7a3a-f3b1-11e7-af8a-ac7ba111b09d/kinect2_bridge-3.log].
log file: /home/ubuntu/.ros/log/181d7a3a-f3b1-11e7-af8a-ac7ba111b09d/kinect2_bridge-3*.log
[kinect2_points_xyzrgb_sd-4] process has died [pid 22192, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb kinect2 rgb/camera_info:=kinect2/sd/camera_info rgb/image_rect_color:=kinect2/sd/image_color_rect depth_registered/image_rect:=kinect2/sd/image_depth_rect depth_registered/points:=kinect2/sd/points __name:=kinect2_points_xyzrgb_sd __log:=/home/ubuntu/.ros/log/181d7a3a-f3b1-11e7-af8a-ac7ba111b09d/kinect2_points_xyzrgb_sd-4.log].
log file: /home/ubuntu/.ros/log/181d7a3a-f3b1-11e7-af8a-ac7ba111b09d/kinect2_points_xyzrgb_sd-4*.log
[kinect2_bridge-3] restarting process
process[kinect2_bridge-3]: started with pid [22403]
[kinect2_points_xyzrgb_sd-4] restarting process
process[kinect2_points_xyzrgb_sd-4]: started with pid [22405]
[ INFO] [1515332763.185250667]: Loading nodelet /kinect2_bridge of type kinect2_bridge/kinect2_bridge_nodelet to manager kinect2 with the following remappings:
[ INFO] [1515332763.195492862]: waitForService: Service [/kinect2/load_nodelet] could not connect to host [ubuntu-Inspiron-5537:56834], waiting...
^C[kinect2_points_xyzrgb_hd-6] killing on exit
[kinect2_points_xyzrgb_qhd-5] killing on exit
[kinect2_points_xyzrgb_sd-4] killing on exit
[kinect2_bridge-3] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
----------------------------------------------------------------------
Can you tell me how to solve this problem ,thanks。

**Comment by Soy-Robotics** [comment]
Hello @66loveslife , Appear this problem I guess theses follow seasons:
1. Kinect v2 need usb3.0, make sure you have meet this condition.
2. And also kinectv2 need rules which should show  `90-kinect2.rules` in `/etc/udev/rules.d/`
3. Had you install libfreenect2? And pass the test application?
And finally can you show me your setup with kinect v2 configuration? I think I need get more information.

**Comment by 66loveslife** [comment]
Hello@SawYer-Robotics ，I am using usb3.0,and I have installed libfreenect2.The command "./bin/Protonect"is work.
I am sorry I don't konw how to show you my setup with kinect v2 configuration.when i finish install libfreenect2.I done the follow command,and come out problem with "roslaunch kinect2_bridge kinect2_bridge.launch"

$ cd ~/catkin_ws/src/
$ git clone https://github.com/code-iai/iai_kinect2.git
$ cd iai_kinect2
$ rosdep install -r --from-paths .
$ cd ~/catkin_ws
$ catkin_make -DCMAKE_BUILD_TYPE="Release"

Today i retry command it came out 

[FATAL] [1515385713.425790208]: Failed to load nodelet '/kinect2_bridge` of type `kinect2_bridge/kinect2_bridge_nodelet` to manager `kinect2'
[kinect2-2] process has died [pid 25943, exit code -11, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=kinect2 __log:=/home/ubuntu/.ros/log/5e668f7e-f42c-11e7-9ed8-ac7ba111b09d/kinect2-2.log].
log file: /home/ubuntu/.ros/log/5e668f7e-f42c-11e7-9ed8-ac7ba111b09d/kinect2-2*.log
[kinect2_bridge-3] process has died [pid 26170, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load kinect2_bridge/kinect2_bridge_nodelet kinect2 __name:=kinect2_bridge __log:=/home/ubuntu/.ros/log/5e668f7e-f42c-11e7-9ed8-ac7ba111b09d/kinect2_bridge-3.log].
log file: /home/ubuntu/.ros/log/5e668f7e-f42c-11e7-9ed8-ac7ba111b09d/kinect2_bridge-3*.log

Can you tell how to do ?  thanks a lot .

**Comment by Soy-Robotics** [comment]
Hello @66loveslife 
Had you check these label? https://github.com/code-iai/iai_kinect2/issues/399, https://github.com/code-iai/iai_kinect2/issues/394

**Comment by 66loveslife** [comment]
Hello @SawYer-Robotics ,I have solved the problem.
I reinstalled the system.and install libfreenect2 and iai_kinect2,then it worked.thank you.

**Comment by Soy-Robotics** [comment]
Ok, I will close this issues, good luck.

**Comment by SinaiAranda** [comment]
Hi @66loveslife this solve the problem without reinstall all system.

```
$ cd ~/catkin_ws
$ catkin_make -DCMAKE_BUILD_TYPE="Release"
```

thanks

**Comment by florianspy** [comment]
I found out you can even use opencv 3.2 but only when cv bridge was also build with opencv 3.2 as it is for ros melodic. So if you have this issue above the opencv version used for building kinect bridge and building cv_bridge of ros do not match. So make them match and this will solve the above issue.
